//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res_Paint_HTML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_Paint_HTML() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control.Properties.Res_Paint_HTML", typeof(Res_Paint_HTML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;drop&quot; data-toggle=&quot;menu&quot; data-title=&quot;{1}&quot; data-type=&quot;{2}&quot; data-idMenu=&quot;{3}&quot;&gt; &lt;a&gt;&lt;span&gt;{0}&lt;/span&gt;&lt;/a&gt; &lt;/li&gt;.
        /// </summary>
        public static string PAINT_AREAS_OPTION_CONTENT {
            get {
                return ResourceManager.GetString("PAINT_AREAS_OPTION_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;drop&quot;&gt;&lt;a&gt;&lt;span&gt;{0}&lt;/span&gt;&lt;/a&gt;{1}&lt;/li&gt;.
        /// </summary>
        public static string PAINT_AREAS_OPTION_HOVER {
            get {
                return ResourceManager.GetString("PAINT_AREAS_OPTION_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;drop&quot; data-toggle=&quot;modal-generic&quot; aria-controls=&quot;ct-radiografias&quot; modal-id=&quot;radiografia_vo&quot;&gt;&lt;a&gt;&lt;span&gt;{0}&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_AREAS_OPTION_MODAL {
            get {
                return ResourceManager.GetString("PAINT_AREAS_OPTION_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;drop&quot; data-toggle=&quot;menu&quot; data-type=&quot;{3}&quot; data-title=&quot;{1}&quot; data-url=&quot;{2}&quot;&gt;&lt;a&gt;&lt;span&gt;{0}&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_AREAS_OPTION_PDF {
            get {
                return ResourceManager.GetString("PAINT_AREAS_OPTION_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;drop&quot; onclick=&quot;window.open(document.getElementById(&apos;opt_{1}&apos;).href);return false;&quot; &gt;&lt;a id=&quot;opt_{1}&quot; href=&quot;{2}&quot;&gt;&lt;span&gt;{0}&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_AREAS_OPTION_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_AREAS_OPTION_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;carousel-control-prev&quot; href=&quot;#bannerCarousel&quot; role=&quot;button&quot; data-slide=&quot;prev&quot;&gt;
        ///                        &lt;span class=&quot;carousel-control-prev-icon&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;
        ///                        &lt;span class=&quot;sr-only&quot;&gt;Previous&lt;/span&gt;
        ///                    &lt;/a&gt;
        ///                    &lt;a class=&quot;carousel-control-next&quot; href=&quot;#bannerCarousel&quot; role=&quot;button&quot; data-slide=&quot;next&quot;&gt;
        ///                        &lt;span class=&quot;carousel-control-next-icon&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;
        ///                        &lt;span class=&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PAINT_BANNER_CONTROLES {
            get {
                return ResourceManager.GetString("PAINT_BANNER_CONTROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;carousel-item {0}&quot; data-toggle=&quot;tooltip&quot; data-placement=&quot;top&quot; title=&quot;{3}&quot;&gt;                          
        ///    &lt;a data-type=&quot;{1}&quot; class=&quot;cursor-pointer&quot;&gt;
        ///    &lt;img src=&quot;{2}&quot; alt=&quot;&quot; class=&quot;w-100&quot;&gt;&lt;/a&gt;
        /// &lt;/div&gt;.
        /// </summary>
        public static string PAINT_BANNER_MODAL_OPCIONES {
            get {
                return ResourceManager.GetString("PAINT_BANNER_MODAL_OPCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;carousel-item {0}&quot; data-toggle=&quot;tooltip&quot; data-placement=&quot;top&quot; title=&quot;{3}&quot;&gt;
        ///    &lt;a  href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;
        ///     &lt;img src=&quot;{2}&quot; alt=&quot;&quot; class=&quot;w-100&quot;&gt;&lt;/a&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string PAINT_BANNER_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_BANNER_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li data-target=&quot;#pageCarousel&quot; data-slide-to=&quot;{0}&quot; {1}&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_CARRUSEL_CONTROLES_LI {
            get {
                return ResourceManager.GetString("PAINT_CARRUSEL_CONTROLES_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ol class=&quot;carousel-indicators&quot;&gt;{0}&lt;/ol&gt;.
        /// </summary>
        public static string PAINT_CARRUSEL_CONTROLES_OL {
            get {
                return ResourceManager.GetString("PAINT_CARRUSEL_CONTROLES_OL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;carousel-item {0}&quot;&gt;&lt;img src=&quot;{1}&quot; class=&quot;d-block w-100&quot; alt=&quot;...&quot;&gt;&lt;/div&gt;.
        /// </summary>
        public static string PAINT_CARRUSEL_PRINCIPAL {
            get {
                return ResourceManager.GetString("PAINT_CARRUSEL_PRINCIPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;tab-pane fade show active&quot; id=&quot;ct_{0}&quot;&gt;&lt;div class=&quot;tab-contenedor-title&quot;&gt; &lt;h1&gt;{1}&lt;/h1&gt; &lt;/div&gt;&lt;div class=&quot;tab-contenedor-body&quot;&gt;&lt;object data=&quot;{2}&quot;&gt;&lt;/object&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string PAINT_CONTENT_TYPE_PDF {
            get {
                return ResourceManager.GetString("PAINT_CONTENT_TYPE_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string PAINT_DESTACADOS_DATA_TYPE {
            get {
                return ResourceManager.GetString("PAINT_DESTACADOS_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-lg-4&quot;&gt;
        ///                    &lt;div class=&quot;item mb-md50&quot;&gt;
        ///                        &lt;div class=&quot;post-img&quot;&gt;
        ///                            &lt;div class=&quot;img&quot;&gt;
        ///                                &lt;div class=&quot;contenedor-img ejemplo-2&quot;&gt;
        ///                                    &lt;img src=&quot;{0}&quot; alt=&quot;&quot; style=&quot;width:300px;&quot;&gt;
        ///                                    &lt;div class=&quot;mascara&quot;&gt;&lt;/div&gt;
        ///                                    &lt;div class=&quot;contenido&quot; style=&quot;margin-top:260px&quot;&gt;
        ///                                        &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PAINT_DESTACADOS_MODAL {
            get {
                return ResourceManager.GetString("PAINT_DESTACADOS_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-lg-4&quot;&gt;
        ///                    &lt;div class=&quot;item mb-md50&quot;&gt;
        ///                        &lt;div class=&quot;post-img&quot;&gt;
        ///                            &lt;div class=&quot;img&quot;&gt;
        ///                                &lt;div class=&quot;contenedor-img ejemplo-2&quot;&gt;
        ///                                    &lt;img src=&quot;{0}&quot; alt=&quot;&quot; style=&quot;width:300px;&quot;&gt;
        ///                                    &lt;div class=&quot;mascara&quot;&gt;&lt;/div&gt;
        ///                                    &lt;div class=&quot;contenido&quot; style=&quot;margin-top:260px&quot;&gt;
        ///                                        &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PAINT_DESTACADOS_MODAL_GENERIC {
            get {
                return ResourceManager.GetString("PAINT_DESTACADOS_MODAL_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-lg-4&quot;&gt;
        ///                    &lt;div class=&quot;item mb-md50&quot;&gt;
        ///                        &lt;div class=&quot;post-img&quot;&gt;
        ///                            &lt;div class=&quot;img&quot;&gt;
        ///                                &lt;div class=&quot;contenedor-img ejemplo-2&quot;&gt;
        ///                                    &lt;img src=&quot;{0}&quot; alt=&quot;&quot; style=&quot;width:300px;&quot;&gt;
        ///                                    &lt;div class=&quot;mascara&quot;&gt;&lt;/div&gt;
        ///                                    &lt;div class=&quot;contenido&quot; style=&quot;margin-top:260px&quot;&gt;
        ///                                        &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PAINT_DESTACADOS_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_DESTACADOS_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-md-2&quot;&gt;
        ///                    &lt;a data-type=&quot;frecuentesAplicativos{0}&quot; href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;
        ///                        &lt;i class=&quot;fa fa-cog fa-spin&quot;&gt;&lt;/i&gt;{2}
        ///                    &lt;/a&gt;
        ///                &lt;/div&gt;.
        /// </summary>
        public static string PAINT_FRECUENTES_APLICATIVOS {
            get {
                return ResourceManager.GetString("PAINT_FRECUENTES_APLICATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div data-type=&quot;{0}&quot; class=&quot;col-md-3 d-flex box-frecuentes p-3 justify-content-between align-items-center&quot;&gt;
        ///                            &lt;img src=&quot;{1}&quot; alt=&quot;&quot; class=&quot;w-25 m-4&quot;&gt;
        ///                            &lt;div class=&quot;vertical-bar&quot;&gt;&lt;/div&gt;
        ///                            &lt;div class=&quot;w-100 d-flex  align-items-center justify-content-center&quot;&gt;
        ///                                &lt;div style=&quot;font-size: 16px;&quot;&gt;{2}&lt;/div&gt;
        ///                            &lt;/div&gt;
        ///                        &lt;/div&gt;.
        /// </summary>
        public static string PAINT_FRECUENTES_DATA_TYPE {
            get {
                return ResourceManager.GetString("PAINT_FRECUENTES_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-md-3 d-flex box-frecuentes p-3 justify-content-between align-items-center&quot; data-toggle=&quot;modal&quot; data-target=&quot;#{0}&quot;&gt;
        ///                            &lt;img src=&quot;{1}&quot; alt=&quot;&quot; class=&quot;w-25 m-4&quot;&gt;
        ///                            &lt;div class=&quot;vertical-bar&quot;&gt;&lt;/div&gt;
        ///                            &lt;div class=&quot;w-100 d-flex  align-items-center justify-content-center&quot;&gt;
        ///                                &lt;div class=&quot;text-center&quot; style=&quot;font-size: 16px;&quot;&gt;{2}&lt;/div&gt;
        ///                            &lt;/div&gt;
        ///                      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PAINT_FRECUENTES_MODAL {
            get {
                return ResourceManager.GetString("PAINT_FRECUENTES_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-md-3 d-flex box-frecuentes p-3 justify-content-between align-items-center&quot;&gt;
        ///                            &lt;img src=&quot;{0}&quot; alt=&quot;&quot; class=&quot;w-25 m-4&quot;&gt;
        ///                            &lt;div class=&quot;vertical-bar&quot;&gt;&lt;/div&gt;
        ///                            &lt;div class=&quot;w-100 d-flex  align-items-center justify-content-center&quot;&gt;
        ///                                &lt;div style=&quot;font-size: 16px;&quot;&gt;&lt;a  href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;&lt;/div&gt;
        ///                            &lt;/div&gt;
        ///                        &lt;/div&gt;.
        /// </summary>
        public static string PAINT_FRECUENTES_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_FRECUENTES_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;nav-item active liMenu&quot;&gt;&lt;a href=&quot;{2}&quot; class=&quot;nav-link cursor-pointer&quot;&gt;{0}&lt;/a&gt;{1} &lt;/li&gt;.
        /// </summary>
        public static string PAINT_MENU_PRINCIPAL {
            get {
                return ResourceManager.GetString("PAINT_MENU_PRINCIPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a id=&quot;{0}&quot; class=&quot;dropdown-item chanGaleria&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string PAINT_OPCIONES_YEAR {
            get {
                return ResourceManager.GetString("PAINT_OPCIONES_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string PAINT_SABER_DATA_TYPE {
            get {
                return ResourceManager.GetString("PAINT_SABER_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-md-3&quot;&gt;
        ///                    &lt;div class=&quot;item&quot;&gt;
        ///                        &lt;span class=&quot;icon&quot; aria-hidden=&quot;true&quot; data-toggle=&quot;modal&quot; data-target=&quot;#{0}&quot;&gt;
        ///                            &lt;i class=&quot;{1}&quot;&gt;&lt;/i&gt;
        ///                        &lt;/span&gt;
        ///                        &lt;h6&gt;{2}&lt;/h6&gt;
        ///                        &lt;p&gt;{3}&lt;/p&gt;
        ///                    &lt;/div&gt;
        ///                &lt;/div&gt;.
        /// </summary>
        public static string PAINT_SABER_MODAL {
            get {
                return ResourceManager.GetString("PAINT_SABER_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;col-md-3&quot;&gt;
        ///                    &lt;div class=&quot;item&quot; &gt;
        ///                        &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;
        ///                            &lt;span class=&quot;icon&quot;&gt;
        ///                                &lt;i class=&quot;{1}&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;                                
        ///                            &lt;/span&gt;
        ///                        &lt;/a&gt;
        ///                        &lt;h6 id=&quot;texto1s&quot;&gt;{2}&lt;/h6&gt;
        ///                        &lt;p&gt;{3}&lt;/p&gt;
        ///                    &lt;/div&gt;
        ///                &lt;/div&gt;.
        /// </summary>
        public static string PAINT_SABER_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_SABER_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;menuChild&quot;&gt;&lt;a data-toggle=&quot;modal&quot; data-target=&quot;{0}&quot;&gt;{1}&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_SUBMENU_PRINCIPAL_MODAL {
            get {
                return ResourceManager.GetString("PAINT_SUBMENU_PRINCIPAL_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;li class=&quot;menuChild&quot;&gt;&lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string PAINT_SUBMENU_PRINCIPAL_REDIRECT {
            get {
                return ResourceManager.GetString("PAINT_SUBMENU_PRINCIPAL_REDIRECT", resourceCulture);
            }
        }
    }
}
